name: Build and push Docker images

on:
  push:    
    tags:
      - 'v*'
      
      
jobs:
  build-and-publish-docker-image:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3.5.0
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'  
          
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
        
      - name: Build app
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: 7.6.1
          arguments: buildFatJar
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/spring-application
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
